### ISSUE TITLE
Web Panel vs WinForms

### ISSUE THREAD

**Issue by developervariety** [developervariety/secureapp#3]

**Comment by dr4k0nia** [comment]
Webpanel is better imo

**Comment by developervariety** [comment]
Why do you feel a web panel is the better way to go?

What are the pros over the WinForms approach?

**Comment by developervariety** [comment]
I will be closing this issue.

I have decided to go with a web panel to avoid any unexpected exceptions on WinForms. Anyone is welcome to create a port based off of the panel. The web panel will be a interface based off of the RESTful API.
