### ISSUE TITLE
Authentication methods or Forms

### ISSUE THREAD

**Issue by developervariety** [developervariety/secureapp#5]

**Comment by developervariety** [comment]
The good old licensing system NetSeal had forms for user authentication, but I want to see what the community rather have. I know some disliked that they could not modify the forms on NetSeal to match the theme.

Comment down your thoughts below!

**Comment by zarlo** [comment]
methods give's dev's more freedom

**Comment by developervariety** [comment]
Alright so if anyone has any other inputs on this just comment below. I'll be closing this for now.
